"""Changed model names

Revision ID: 6065428b7f94
Revises: b5dc6f113f4d
Create Date: 2024-03-02 17:50:55.723525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6065428b7f94'
down_revision = 'b5dc6f113f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpucooler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.drop_table('cpu_cooler')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu_cooler',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('rpm', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.drop_table('cpucooler')
    # ### end Alembic commands ###
