"""pc builds as model

Revision ID: 74bf32ff5ffb
Revises: fda50526d951
Create Date: 2024-04-07 17:47:43.443038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '74bf32ff5ffb'
down_revision = 'fda50526d951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcbuild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_case',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'case_id')
    )
    op.create_table('build_cpu',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('cpu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'cpu_id')
    )
    op.create_table('build_cpucooler',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('cpucooler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['cpucooler_id'], ['cpucooler.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'cpucooler_id')
    )
    op.create_table('build_drive',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['drive.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'drive_id')
    )
    op.create_table('build_fans',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('fans_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['fans_id'], ['fans.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'fans_id')
    )
    op.create_table('build_gpu',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'gpu_id')
    )
    op.create_table('build_mobo',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('mobo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['mobo_id'], ['mobo.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'mobo_id')
    )
    op.create_table('build_psu',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('psu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['psu_id'], ['psu.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'psu_id')
    )
    op.create_table('build_ram',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('ram_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pcbuild.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['ram.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'ram_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pc_build')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pc_build', sqlite.JSON(), nullable=True))

    op.drop_table('build_ram')
    op.drop_table('build_psu')
    op.drop_table('build_mobo')
    op.drop_table('build_gpu')
    op.drop_table('build_fans')
    op.drop_table('build_drive')
    op.drop_table('build_cpucooler')
    op.drop_table('build_cpu')
    op.drop_table('build_case')
    op.drop_table('pcbuild')
    # ### end Alembic commands ###
