"""Initial Setup

Revision ID: b5dc6f113f4d
Revises: 
Create Date: 2023-12-28 17:24:39.786290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5dc6f113f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('side_panel', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('cpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('clockSpeed', sa.Float(precision=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('cpu_cooler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('drive_type', sa.String(length=10), nullable=True),
    sa.Column('interface', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('gpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('chipset', sa.String(length=50), nullable=True),
    sa.Column('mem', sa.Integer(), nullable=True),
    sa.Column('core_clock', sa.Integer(), nullable=True),
    sa.Column('gpu_len', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('mobo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('mem_slot', sa.Integer(), nullable=True),
    sa.Column('socket_type', sa.String(length=20), nullable=True),
    sa.Column('form_factor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('psu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('form_factor', sa.String(length=5), nullable=True),
    sa.Column('effi', sa.String(length=10), nullable=True),
    sa.Column('wattage', sa.Integer(), nullable=True),
    sa.Column('mod', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('ram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('modules', sa.String(length=20), nullable=True),
    sa.Column('cas_latency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_pfp', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ram')
    op.drop_table('psu')
    op.drop_table('mobo')
    op.drop_table('gpu')
    op.drop_table('fans')
    op.drop_table('drive')
    op.drop_table('cpu_cooler')
    op.drop_table('cpu')
    op.drop_table('case')
    # ### end Alembic commands ###
