"""empty message

Revision ID: fda50526d951
Revises: 6e3196c3a983
Create Date: 2024-03-22 16:35:11.407685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda50526d951'
down_revision = '6e3196c3a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pc_build')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pc_build', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pc_build')

    op.create_table('pc_build',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('cpu_id', sa.INTEGER(), nullable=True),
    sa.Column('cpucooler_id', sa.INTEGER(), nullable=True),
    sa.Column('mobo_id', sa.INTEGER(), nullable=True),
    sa.Column('gpu_id', sa.INTEGER(), nullable=True),
    sa.Column('ram_id', sa.INTEGER(), nullable=True),
    sa.Column('drive_id', sa.INTEGER(), nullable=True),
    sa.Column('psu_id', sa.INTEGER(), nullable=True),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('fans_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu.id'], ),
    sa.ForeignKeyConstraint(['cpucooler_id'], ['cpucooler.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['drive.id'], ),
    sa.ForeignKeyConstraint(['fans_id'], ['fans.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu.id'], ),
    sa.ForeignKeyConstraint(['mobo_id'], ['mobo.id'], ),
    sa.ForeignKeyConstraint(['psu_id'], ['psu.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['ram.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
